# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a5b668679e4b00b4721020616b0fbdba0cc70475e2dd3cd21d87f57638eec41e6e71f765959bd09099f3d9e88e7833af42aad23d1a14c63b97e9e99ced5f7bb

test:
  secret_key_base: 1e385381f72bd9c0178e6cb2ba5e60945d932e192c700e845bf36763af80bc80da592ee4e9793c557f496f16a1ea96762b2d4dd9cdd773001d9874d8707160e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
